spring:
  datasource:
    url: jdbc:h2:~/super_hero
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:h2/init.sql
    initialization-mode: always
